spring.application.name=RMS
# Server port
Server.port = 8080

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/RMS_backend
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# local h2 tables setup on startup; use the value "none" in production!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=125429871805-74d8nc2hbg1p3eucotjns1cfv07h1ntj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google
# spring.security.oauth2.client.registration.google.login-page=/login

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=debp.6640@gmail.com
spring.mail.password=qssg tssf pxzs znwt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.api.key=sk_test_51REn9g4F19d3jQ1bDILJQfrqx2VHF25b1J8o13nsQ2BiKL8mTYp9uWaFU39KEMoFafPjQ179CtN4qG3EhBBpfJk800lE7spQWf

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json
